# Generated by Django 3.2.12 on 2022-05-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[(0, '기타'), (1, '교육자'), (2, '예술가'), (3, '사무관리직'), (4, '대학생/대학원생'), (5, '서비스업'), (6, '의사/의료계'), (7, '임원/관리자'), (8, '농부'), (9, '전업주부'), (10, '청소년/학생'), (11, '법조인'), (12, '프로그래머'), (13, '은퇴'), (14, '영업/마케팅'), (15, '과학자'), (16, '프리랜서'), (17, '기계공/엔지니어'), (18, '소상공인'), (19, '무직'), (20, '작가')], default=0, max_length=50),
        ),
    ]
