# Generated by Django 3.2.12 on 2022-05-25 04:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('backdrop_path', models.TextField()),
                ('genres', models.TextField()),
                ('runtime', models.IntegerField()),
                ('tagline', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(max_length=100)),
                ('vote_average', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('revenue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Moviedata',
            fields=[
                ('movieId', models.IntegerField(primary_key=True, serialize=False)),
                ('tmdbId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
